import Head from "next/head";
import Banner from "../components/Home/Banner";
import BestBurger from "../components/Home/BestBurger";
import ClientSay from "../components/Home/ClientSay";
import TastyFood from "../components/Home/TastyFood";
import JoinUs from "../components/Home/JoinUs";
import Menus from "../components/Home/Menus";
import Special from "../components/Home/Special";
import TopRecipes from "../components/Home/TopRecipes";
import styles from "../styles/Home.module.css";
import DishesMenu from '../components/Home/DishesMenu'


export default function Home({foods,reviews}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Menus />
      <Special />
      <DishesMenu foods={foods}/>
      <TastyFood />
      <TopRecipes foods={foods}/>
      <ClientSay/>
      <BestBurger />
      <JoinUs />
    </div>
  );
}

export async function getServerSideProps(ctx){
  const res = await fetch('http://localhost:3000/api/foods')
  const data = await res.json();
  // const reviewsRes = await axios.get('http://localhost:3000/api/reviews')

  return {
    props:{
      foods:data,
      // reviews:reviewsRes.data
    }
  }
}
