import Head from 'next/head'
import Banner from '../components/Home/Banner'
import HotDog from '../components/Home/HotDog'
import Menus from '../components/Home/Menus'
import Special from '../components/Home/Special'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <Menus/>
      <Special/>
      <HotDog/>
    </div>
  )
}
